<script lang="ts">
	import { onMount } from 'svelte';
	import Reveal from 'reveal.js';
	import Markdown from 'reveal.js/plugin/markdown/markdown';
	let deck;
	onMount(() => {
		deck = new Reveal({
			plugins: [Markdown]
		});

		deck.initialize();
	});

	let today = new Date();
	let options: Intl.DateTimeFormatOptions = {
		weekday: 'long',
		month: 'short',
		day: '2-digit',
		year: 'numeric'
	};
	let dateString = today.toLocaleDateString('en-US', options);
</script>

<div class="reveal">
	<div class="slides">
		<section>
			<p>Microwave Plasma Pyrolysis Systems 🔥 for Waste Treatment in Delhi</p>
			<p class="capitalize">Joseph Kamalesh</p>
			<p>Date - {dateString}</p>
			<p class="capitalize">Occasion of the presentation: Investor Meeting</p>
		</section>
		<section>
			<h2>Introduction</h2>
			<ul>
				<li>
					Briefly introduce the topic of microwave plasma pyrolysis systems for waste treatment
				</li>
				<li>
					Explain the significance of this technology in the context of Delhi's waste management
					problem
				</li>
				<li>Highlight that you will be answering 8 key questions from the investors</li>
			</ul>
		</section>
	</div>
</div>
<!-- 
<div class="reveal">
	<div class="slides">
		<p>Microwave Plasma Pyrolysis Systems 🔥 for Waste Treatment in Delhi</p>
		<p class="capitalize">Joseph Kamalesh</p>
		<p>Date - {dateString}</p>
		<p class="capitalize">Occasion of the presentation: Investor Meeting</p>
	</div>
	<div class="slides">
		<h2>Introduction</h2>
		<ul>
			<li>Briefly introduce the topic of microwave plasma pyrolysis systems for waste treatment</li>
			<li>
				Explain the significance of this technology in the context of Delhi's waste management
				problem
			</li>
			<li>Highlight that you will be answering 8 key questions from the investors</li>
		</ul>
	</div>
	<div class="slides">
		<h2>
			Question 1: How will the government of Delhi and the citizens of Delhi benefit from this
			project?
		</h2>
		<ul>
			<li>
				Microwave pyrolysis technology can offer a creative solution to Delhi's waste problem by
				transforming waste into wealth.
			</li>
			<li>
				It can provide a service that enables 100% diversion of waste from landfills, reduce
				environmental and health impacts, process any type of waste, recycle it up to 100%, and
				produce syngas from trash which can be used to generate electricity and heat.
			</li>
		</ul>
	</div>
	<div class="slides">
		<h2>
			Question 2: What are the technical specifications and operational parameters of the microwave
			plasma pyrolysis system?
		</h2>
		<ul>
			<li>
				The technical specifications and operational parameters of the microwave plasma pyrolysis
				system include its design, capacity, efficiency, reliability, safety, and environmental
				performance.
			</li>
			<li>
				The system is based on a modular and scalable design that can process different types and
				quantities of waste using microwave radiation and plasma torches.
			</li>
			<li>
				The system can achieve high conversion rates, low emissions, and high energy recovery.
			</li>
		</ul>
	</div>
	<div class="slides">
		<h2>
			Question 3: What are the types and quantities of waste that can be processed by the system?
		</h2>
		<ul>
			<li>
				The microwave plasma pyrolysis system can process any type of waste liquid or solid other
				than explosives and radioactive materials.
			</li>
			<li>
				The system can handle municipal solid waste, industrial waste, hazardous waste, biomedical
				waste, electronic waste, plastic waste, organic waste, and inorganic waste.
			</li>
			<li>
				The system can process up to 10 tons of waste per day in its pilot plant configuration.
			</li>
		</ul>
	</div>

	<div class="slides">
		<h2>
			Question 4: What are the types and quantities of products that can be generated by the system?
		</h2>
		<ul>
			<li>
				The microwave plasma pyrolysis system can generate valuable products such as syngas,
				bio-oil, and biochar from waste.
			</li>
			<li>These products can be used as fuels, chemicals, or soil amendments.</li>
			<li>
				The system can produce up to 2 MW of electricity and 1 ton of biochar per day from 10 tons
				of waste.
			</li>
		</ul>
	</div>

	<div class="slides" id="list">
		<h2>
			Question 5: What are the environmental impacts of the system compared to other waste
			management options?
		</h2>
		<ul>
			<li>
				The environmental impacts of the microwave plasma pyrolysis system are significantly lower
				than those of other waste management options such as landfilling or incineration.
			</li>
			<br />
			<li>
				The system can reduce greenhouse gas emissions, air pollution, water pollution, soil
				contamination, and resource depletion.
			</li>
			<br />
			<li>
				The system can also contribute to climate change mitigation, biodiversity conservation, and
				sustainable development.
			</li>
			<br />
		</ul>
		<br />
		<p>Next slide for Question 6...</p>
		<br />
	</div>

	<div class="slides" id="list">
		<h2>
			Question 6: What are the economic aspects of the system such as capital and operating costs
			revenue streams payback period and return on investment?
		</h2>
		<br />
		<ul>
			<li>
				The economic aspects of the microwave plasma pyrolysis system include its capital and
				operating costs revenue streams payback period and return on investment.
			</li>
			<br />
			<li>
				The system has high capital costs due to its advanced technology and equipment but low
				operating costs due to its high efficiency and automation.
			</li>
			<br />
			<li>
				The system can generate revenue from the sale of electricity heat biochar carbon credits
				tipping fees or subsidies.
			</li>
			<br />
			<li>
				The payback period and return on investment depend on various factors such as market
				conditions policy support or financing options.
			</li>
			<br />
		</ul>
	</div>

	<div class="slides" id="list">
		<h2>
			Question 7: What are the social aspects of the system such as job creation public health
			improvement community engagement and stakeholder involvement?
		</h2>
		<ul>
			<li>
				The social aspects of the microwave plasma pyrolysis system include its potential to create
				jobs improve public health engage communities involve stakeholders.
			</li>
			<li>
				The system can create direct indirect induced jobs in various sectors such as engineering
				construction operation maintenance research development marketing sales or services.
			</li>
			<li>
				The system can improve public health by reducing air water soil pollution improving
				sanitation hygiene preventing diseases improving nutrition or enhancing well-being.
			</li>
		</ul>
	</div>

	<div class="slides" id="list">
		<h2>
			Question 8: What are the challenges and risks associated with the implementation of the system
			and how can they be overcome?
		</h2>
		<ul>
			<li>
				The challenges risks associated with implementation microwave plasma pyrolysis system
				include technical financial regulatory social environmental market or institutional
				challenges risks.
			</li>
			<li>
				These challenges risks can be overcome by adopting best practices conducting rigorous
				research engaging stakeholders developing supportive policies securing adequate funding
				building strong partnerships or demonstrating successful pilots.
			</li>
		</ul>
	</div>

	<div class="slides" id="list">
		<h2>Additional Insights</h2>
		<br />
		<ul>
			<li>
				Microwave plasma pyrolysis systems for waste treatment offer multiple benefits such as waste
				reduction, resource recovery, energy generation, emission reduction, job creation, or
				revenue generation.
			</li>
			<br />
		</ul>
		<br />
		<li>Challenges:</li>
		<br />
		<ul>
			<li>
				Microwave plasma pyrolysis systems for waste treatment face several challenges such as high
				capital costs, technical complexity, regulatory uncertainty, social acceptance, or market
				development.
			</li>
			<br />
		</ul>
		<br />
		<li>Case Studies:</li>
		<br />
		<ul>
			<li>
				There are several successful case studies of microwave plasma pyrolysis systems for waste
				treatment in countries such as Japan, Germany, Canada, or the USA.
			</li>
			<br />
		</ul>
		<br />
		<li>Specific Implications for Delhi:</li>
		<br />
		<ul>
			<li>
				The implementation of microwave plasma pyrolysis systems for waste treatment in Delhi can
				have specific implications such as improving the city's waste management system enhancing
				its environmental performance boosting its economic growth or improving its social welfare.
			</li>
			<br />
		</ul>
		<br />
	</div>

	<div class="slides" id="list">
		<h2>Recommendations and Conclusion</h2>
		<br />
		<ul>
			<li>
				Based on the answers to the questions and the additional insights it is recommended that the
				government of Delhi and the investors support the implementation of microwave plasma
				pyrolysis systems for waste treatment in Delhi.
			</li>
			<br />
			<li>
				The technology offers a viable and sustainable solution to Delhi's waste management problem
				and can contribute to its economic environmental and social development.
			</li>
			<br />
			<li>
				The project proposed by Carbotura provides a solid and credible basis for scaling up the
				technology in Delhi and other cities in India.
			</li>
			<br />
		</ul>
	</div>

	<div class="slides">
		<h2>Q&A Slide</h2>
		<p>Invite further questions or discussion from the audience.</p>
	</div>
</div> -->
